# main.yml
name: deploy to linux server
on:
  push:
    branches:
      - main

permissions:
  contents: write
  discussions: write

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
          cache: true

      - name: Build
        run: |
          go build -o demoreleaser

      # Deploy
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v4.0.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "./demoreleaser"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: "/data/demor/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT

      - name: Update the API service
        uses: appleboy/ssh-action@v0.0.6
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            whoami
            cd /data/demor/ && nohup ./demoreleaser > nohup.out 2> nohup.err < /dev/null &
            ls -la